app:
  image: 'registry-vpc.cn-hangzhou.aliyuncs.com/yitong-dev/yitong-com-qr:latest'
  restart: always
  volumes:
    - '/etc/timezone:/etc/timezone:ro'
    - '/etc/localtime:/etc/localtime:ro'
  environment:
    - 'constraint:yitong.node==app'
  hostname: 'yitong-com-qr'